# Generated by Django 5.1.3 on 2026-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
