# Generated by Django 5.1.3 on 2026-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='autor',
            field=models.CharField(default='Anônimo', max_length=80),
        ),
    ]
