# Generated by Django 5.1.3 on 2026-07-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_categoria_mensagem_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mensagens', to='home.tag'),
        ),
    ]
